16 - Implemento parametro heroImageUrl del TSExplorer
datosgobar/ckanext-seriestiempoarexplorer pull request #17
Opened 2019-09-30 20:03 UTC by pepeciavirella

Comienzo a usar el nuevo parámetro del `TSExplorer`, `heroImageUrl`, para indicarle qué imagen usar de fondo para el banner del encabezado. Para ello:

- Actualizo la versión usada del Explorer a la 2.5.1
- Saco selectores de CSS para el `container`, ya que ahora es el div `hero-caption` quien se encarga de aplicar la transparencia a la imagen de fondo, y dicha imagen se pasa al `TSExplorer` en el tag de script.
- Le paso la variable `bgUrl`, que tiene la URL de la imagen a usar en el Explorer, al componente `TSExplorer` renderizado.

Closes #16

2019-09-30 20:15 UTC, lrromero approved these changes

2019-10-01 17:38 UTC, chdigiorno requested changes

2019-10-01 17:38 UTC, chdigiorno commented on ckanext/seriestiempoarexplorer/templates/seriestiempoarexplorer/series_explorer.html
> +               Trimestral: "{{ h.get_theme_config('series_tiempo_ar_explorer.laps.mensual') or 24 }}",
Te quedó lo mismo que en Mensual

2019-10-03 16:59 UTC, chdigiorno approved these changes

2019-10-03 17:34 UTC, merged